### ISSUE TITLE
Неизвестный баланс

### ISSUE THREAD

**Issue by arynyklas** [Anonymousl33t/bitgenModifed#3]
Не показывает баланс, нет доступа к сайту. Пробовал разные VPN'ы и прокси, не помогает

**Comment by KENTua** [comment]
Автору плевать. Он знал об этом ещё с самого начала. 

Говнокод дабы 'поиметь' авторитет у школьников

**Comment by arynyklas** [comment]
> 
> 
> Автору плевать. Он знал об этом ещё с самого начала.
> 
> Говнокод дабы 'поиметь' авторитет у школьников.
> Ещё и на какой-то болт 🔩 в архив засунул

Я это понял, оно реально говно, но я сделал свой тут в телеге: https://t.me/pyBTC, оцени плиз )
